/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SelectDescription =
  {
      entity: {
        filters?: ExprDescription[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      agent?: {
        filters?: ExprDescription[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    }
  | {
      location: {
        filters?: ExprDescription[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
export type RuleDescription =
  | {
      description?: string;
      constrains?:
        | {
            entity: {
              [k: string]: string;
            };
          }
        | {
            agent: {
              [k: string]: string;
            };
          }
        | {
            location: {
              [k: string]: string;
            };
          };
      constraints?: ExprDescription[];
    }
  | {
      description?: string;
      when:
        | {
            /**
             * @minItems 1
             */
            all: [ExprDescription, ...ExprDescription[]];
            [k: string]: unknown;
          }
        | {
            /**
             * @minItems 1
             */
            any: [ExprDescription, ...ExprDescription[]];
            [k: string]: unknown;
          }
        | ExprDescription;
      then: [ExprDescription, ...ExprDescription[]] | ExprDescription;
    };

export interface BoardMLGameSpecTopLevelDescription {
  metadata: {
    id: string;
    version: number;
    description?: string;
    tags?: string[];
    [k: string]: unknown;
  };
  parameters?: {
    [k: string]: string | number | boolean;
  };
  rng?: SrcJsonSchemasRngSchemaJson;
  agents:
    | {
        min?: number;
        max?: number;
      }
    | {
        exactly?: number;
      };
  locations: {
    [k: string]: AreaDescription;
  };
  entityTypes?: EntityDescription[];
  /**
   * @minItems 1
   */
  actions: [ActionDescription, ...ActionDescription[]];
  rules: {
    [k: string]: RuleDescription;
  };
  [k: string]: unknown;
}
export interface SrcJsonSchemasRngSchemaJson {
  [k: string]: unknown;
}
export interface AreaDescription {
  links?: string[];
  shape?: {
    rows: number;
    cols: number;
    state?: {
      [k: string]: unknown;
    };
  };
  state?: {
    [k: string]: unknown;
  };
  tags?: string[];
}
export interface EntityDescription {
  id: string;
  state?: {
    [k: string]: number | string | boolean;
  };
  [k: string]: unknown;
}
export interface ActionDescription {
  id: string;
  label?: string;
  tags?: string[];
  /**
   * Sequence of steps to execute as part of this action
   */
  parameters?: {
    [k: string]: SelectDescription;
  };
  [k: string]: unknown;
}
export interface ExprDescription {
  expr: string;
  explain?: string;
  [k: string]: unknown;
}
