/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PhaseNodeDescription {
  id: string;
  label?: string;
  enabledActions?: string[];
  onEnter?: EffectDescription[];
  onExit?: EffectDescription[];
  transitions?: TransitionDescription[];
  [k: string]: unknown;
}
export interface EffectDescription {
  expr: string;
  chance?: number;
  if?: ExprDescription;
  [k: string]: unknown;
}
export interface ExprDescription {
  expr: string;
  explain?: string;
  [k: string]: unknown;
}
export interface TransitionDescription {
  /**
   * @minItems 1
   */
  from: [string, ...string[]];
  to: string;
  trigger: ExprDescription;
}
