/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TriggerDescription {
  id?: string;
  effects?: EffectDescription[];
  /**
   * Times this trigger can fire per turn/game
   */
  limit?: number;
}
export interface EffectDescription {
  expr: string;
  chance?: number;
  if?: ExprDescription;
  [k: string]: unknown;
}
export interface ExprDescription {
  expr: string;
  explain?: string;
  [k: string]: unknown;
}
